// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVJ1R_u6mUPerpwfxmJCEnUa3CcCN2aVY',
    appId: '1:320877596211:web:27b3fe0db75b8bb6b29d46',
    messagingSenderId: '320877596211',
    projectId: 'smartfood-llm-app',
    authDomain: 'smartfood-llm-app.firebaseapp.com',
    storageBucket: 'smartfood-llm-app.firebasestorage.app',
    measurementId: 'G-NC745YFDNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYaX96GzEZscz1HGjooFG8wyQWoCoUsMs',
    appId: '1:320877596211:android:8fe55d419a5a3c36b29d46',
    messagingSenderId: '320877596211',
    projectId: 'smartfood-llm-app',
    storageBucket: 'smartfood-llm-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVUcylroJtLuok5mGLxLC6bPHQ4o8ApuA',
    appId: '1:320877596211:ios:e07f0befaf4dac38b29d46',
    messagingSenderId: '320877596211',
    projectId: 'smartfood-llm-app',
    storageBucket: 'smartfood-llm-app.firebasestorage.app',
    iosBundleId: 'com.example.smartfood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVUcylroJtLuok5mGLxLC6bPHQ4o8ApuA',
    appId: '1:320877596211:ios:e07f0befaf4dac38b29d46',
    messagingSenderId: '320877596211',
    projectId: 'smartfood-llm-app',
    storageBucket: 'smartfood-llm-app.firebasestorage.app',
    iosBundleId: 'com.example.smartfood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVJ1R_u6mUPerpwfxmJCEnUa3CcCN2aVY',
    appId: '1:320877596211:web:bd93027f248f13deb29d46',
    messagingSenderId: '320877596211',
    projectId: 'smartfood-llm-app',
    authDomain: 'smartfood-llm-app.firebaseapp.com',
    storageBucket: 'smartfood-llm-app.firebasestorage.app',
    measurementId: 'G-XN9RRDHVZJ',
  );
}
